### ISSUE TITLE
Could not open input file: /var/www/html/admin/cli/install.php

### ISSUE THREAD

**Issue by andrea-daru** [erseco/alpine-moodle#17]
"Could not open input file: /var/www/html/admin/cli/install.php" error if i try to persist on the local filesystem the moodle folder.
Someone experiencing the same error? Any help would be appreciated.

**Comment by iverybee** [comment]
Same problem here

**Comment by erseco** [comment]
Can you provide the commands you both are using to run the container? I'm using the provided **docker-compose.yml** and running a `docker-compose pull && docker-compose up` runs without problem for me.
Best!

**Comment by iverybee** [comment]
I am using docker-compose up. I need to work with version 3.9 and need access to `www/html/local/.../ `because I am developing a plugin. 
Do you have any idea how I can fix this error? 

Here is the compose file:

```
version: '2'
services:

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_DB=moodle
    volumes:
      - postgres:/var/lib/postgresql/data

  moodle:
    image: moodle-39:latest
    build: .
    restart: unless-stopped
    environment:
      - LANG=de_DE.UTF-8
      - LANGUAGE=de_DE:de
      - SITE_URL=https://moodle.quercom.myds.me
      - DB_TYPE=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=moodle
      - DB_PREFIX=mdl_
      - SSLPROXY=true
      - MOODLE_EMAIL=user@example.com
      - MOODLE_LANGUAGE=de
      - MOODLE_SITENAME=quercom-Moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=#x52&v2pqpyyrW4FCE@m69Tz&rv$gaLHtDBk&^Zg
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=voldemord.sycromoft@gmail.com
      - SMTP_PASSWORD=pbbejknuwhynmjmu \
      - SMTP_PROTOCOL=tls
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@quercom.me
      - MOODLE_MAIL_PREFIX=[moodle]
    ports:
      - 8088:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodledata:/var/www/html
    depends_on:
      - postgres

volumes:
  postgres: null
  moodledata: null
  moodlehtml: null
```

and Dockerfile:

```
ARG ARCH=
FROM ${ARCH}erseco/alpine-php7-webserver

LABEL maintainer="Ernesto Serrano <info@ernesto.es>"

USER root
COPY --chown=nobody rootfs/ /

# crond needs root, so install dcron and cap package and set the capabilities
# on dcron binary https://github.com/inter169/systs/blob/master/alpine/crond/README.md
RUN apk add --no-cache dcron libcap && \
    chown nobody:nobody /usr/sbin/crond && \
    setcap cap_setgid=ep /usr/sbin/crond

USER nobody

# Change MOODLE_38_STABLE for new versions
ENV MOODLE_URL=https://github.com/moodle/moodle/archive/MOODLE_39_STABLE.tar.gz \
    LANG=de_DE.UTF-8 \
    LANGUAGE=de_DE:de \
    SITE_URL=https://moodle.quercom.myds.me \
    DB_TYPE=pgsql \
    DB_HOST=postgres \
    DB_PORT=5432 \
    DB_NAME=moodle \
    DB_USER=moodle \
    DB_PASS=moodle \
    DB_PREFIX=mdl_ \
    SSLPROXY=false \
    MOODLE_EMAIL=user@example.com \
    MOODLE_LANGUAGE=en \
    MOODLE_SITENAME=New-Site \
    MOODLE_USERNAME=moodleuser \
    MOODLE_PASSWORD=PLEASE_CHANGEME \
    SMTP_HOST=smtp.gmail.com \
    SMTP_PORT=587 \
    SMTP_USER=your_email@gmail.com \
    SMTP_PASSWORD=your_password \
    SMTP_PROTOCOL=tls \
    MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost \
    MOODLE_MAIL_PREFIX=[moodle] \
    client_max_body_size=50M \
    post_max_size=50M \
    upload_max_filesize=50M \
    max_input_vars=1000

RUN curl --location $MOODLE_URL | tar xz --strip-components=1 -C /var/www/html/


```
