### ISSUE TITLE
Unable to Create New Role with "Incorrect role short name"

### ISSUE THREAD

**Issue by jimsihk** [erseco/alpine-moodle#26]
Hi,

When defining new roles, it will always rejected by "Incorrect role short name". I tried using the docker-compose.yaml with moodle 4.0 version up to the latest are still facing the same problem.

For comparison, I tried picking the [bitnami stack from GCP](https://console.cloud.google.com/marketplace/product/bitnami-launchpad/moodle) and it works without this issue. Do you think is related to NGINX and MariaDB? I don't have a chance yet to test the [bitnami moodle container](https://github.com/bitnami/containers/tree/main/bitnami/moodle) though.

I also notice that there is an issue logged on official tracker as [MDL-77369](https://tracker.moodle.org/plugins/servlet/mobile#issue/MDL-77369) and the issue seems related to container only.

Any thought?

**Comment by erseco** [comment]
Is possible that the problem is caused because we are using postgresql instead of mariadb, can you please check if with MariaDB it works?

**Comment by lupa18** [comment]
I think is a moodle error and I am who opened [MDL-77369](https://tracker.moodle.org/plugins/servlet/mobile#issue/MDL-77369). Please vote, watch or add comment there :smiley:

**Comment by jimsihk** [comment]
That is what I doubt actually. I did tried a 4.0 GCP Marketplace stack (not docker) and there is no issue, but the same version on docker faces the issue.

Also, not sure if help, I tried [moosh](https://moosh-online.com) and it could create new roles as well from command line (might be a workaround for now?).

@lupa18 how did you bypass the issue?

**Comment by lupa18** [comment]
@jimsihk I'm still waiting :-/

**Comment by jimsihk** [comment]
I tried to set PHP `max_input_vars` to even higher at 100000 but seems not related.

**Comment by erseco** [comment]
I was checking if was problem with the PHP version (8.0) and the moodle version but seems is not related 

I was debugging and seems the root problem can be in the `https://github.com/moodle/moodle/blob/master/admin/roles/classes/define_role_table_basic.php` file or in the `https://github.com/moodle/moodle/blob/master/admin/roles/define.php` but no idea on what is happening

By the way I setted up a new upstream version (4.1.2+) and PHP 8.1 but the problem persists, I will continue testing it, any news I will write here

**Comment by jimsihk** [comment]
Unfortunately, I tried with PHP8.1 and 4.1.2 still the same.

**Comment by erseco** [comment]
Added a message to move this!

**Comment by jimsihk** [comment]
I managed to test the [bitnami docker](https://github.com/bitnami/containers/tree/main/bitnami/moodle) but it works, so it seems not really related to Moodle code itself?

```
version: '2'
services:

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_DB=moodle
    volumes:
      - postgres:/var/lib/postgresql/data

  moodle:
    image: bitnami/moodle
    restart: unless-stopped
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=postgres
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
    ports:
      - 80:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    depends_on:
      - postgres

volumes:
  postgres: null
  moodledata: null
  moodlehtml: null
```
