### ISSUE TITLE
Help with Nginx Proxy Manager setup

### ISSUE THREAD

**Issue by ilanzel** [erseco/alpine-moodle#51]
Hi
As per your advice, I am trying to set Nginx Proxy Manager as a reverse proxy for your container.
I have set up the ports in the docker-compose.yml file to 8080:8080 and 8443:8443 and directed the npm to port 8443, and the SSLPROXY env value to true.
However, I keep getting "Bad Gateway" screens when pointing to my URL.
Any advice?

**Comment by erseco** [comment]
Hi @ilanzel ,

Thanks for reaching out. It sounds like there might be some misconfiguration causing the "Bad Gateway" issue.

To better assist you, could you please share your `docker-compose.yml` (make sure to redact any sensitive information)? This will help in identifying if there's any error in the way the services are set up.

Additionally, it might be useful to check the logs of both the Nginx Proxy Manager and the target container to see if they provide more insights into the problem.

Looking forward to helping you resolve this.

Best!

**Comment by erseco** [comment]
Hello @ilanzel ,

Based on the information provided and the issues you're facing:

1. **Nginx Proxy Manager (NPM) Configuration**:
    - Ensure that the NPM is forwarding to the 8080 port of the moodle nginx server. When you set up your proxy host in NPM, the forwarding URL should be something like `http://<moodle_container_name_or_ip>:8080`. Stop exposing 7443 on the alpine-moodle container, is not needed

2. **Alpine Moodle Configuration**:
    - Within your `docker-compose.yml` for the `alpine-moodle` service, set the `SSLPROXY` environment variable to `false`. This tells Moodle that it's not directly handling SSL (since that's being managed by the NPM) but instead expects non-SSL (HTTP) traffic. Please, read this about turning on SSL: https://docs.moodle.org/403/en/Configuration_file#Setting_.24CFG-.3Ewwwroot_correctly

        ```yaml
        environment:
          ...
          - SSLPROXY=false
          ...
        ```

3. **Moodle Configuration Update**:
    - You might need to update your `config.php` for Moodle to recognize that it's being accessed through a reverse proxy. Add the following line to your `config.php`:

        ```php
        $CFG->reverseproxy = true;
        ```

This configuration tells Moodle to trust the headers provided by the reverse proxy (NPM in this case) and not to second-guess the base URL or client IP address.

After making these adjustments, restart the containers and try accessing your Moodle instance through the NPM.

If these solutions address the issues you're encountering, please tell me to update the `alpine-moodle` container to support the reverse proxy configuration flag natively. This would help streamline the setup process for users in similar situations.

Please let me know if this resolves your problem!

**Comment by erseco** [comment]
#54

**Comment by ilanzel** [comment]
Hello @erseco 
Your advice was very helpful.
It works after changing the ENV variable SSLPROXY=false, and modifying the NPM protocol to HTTP instead of HTTPS.
No need for modification of config.php.
Thanks for that!
However, it seems that the cron job is not working properly, this is the relevant log:

PHP Warning:  Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
/usr/sbin/crond 4.5 dillon's cron daemon, started with loglevel notice
run: cron: (pid 26) 5s
exit status 1 from user nobody /usr/bin/php81  /var/www/html/admin/cli/cron.php > /dev/null

Any thoughts?
Thanks again and best regards

**Comment by erseco** [comment]
Hello @ilanzel,

I'm glad to hear that the advice helped in resolving your initial concerns. Regarding the new issue with the cron job, it appears there is a problem with setting the memory limit. The latest 4.3.0 release has addressed such issues, so updating to this version might solve the problem.

Additionally, there have been updates on the beta/master tag that might interest you. Now, when you alter settings in the `docker-compose.yml` file, the Moodle configuration will be updated upon the next boot. This feature streamlines the configuration process, making it more efficient.

Moreover, new scripts have been introduced to facilitate user enrolment and admin password changes, which should enhance the management of your Moodle environment.

Should you decide to apply these updates, please ensure to backup your current setup to prevent any potential data loss or further issues. Feel free to reach out if you encounter any challenges or have more questions. 

Thanks again for your feedback and best regards!

**Comment by jjrbfi** [comment]
Hi, I commented here because I don't want to disturb creating a new Issue when it is probably not necessary, and there are already issues with some hints that didn't helped me, as for example: (https://github.com/erseco/alpine-moodle/issues/51 , https://github.com/erseco/alpine-moodle/issues/43).

I'm facing a issue when enabling `REVERSEPROXY` in NPM (The two containers are in the same network). It shows me:

![image](https://github.com/erseco/alpine-moodle/assets/71790456/9ede0322-52d0-4a1c-96ed-45f083c61e6c)

I have tried enabling and disabling `SSLPROXY` option, as well adding https and http in the [SITEURL](https://github.com/erseco/alpine-moodle/blob/16da963b981f5786640d3bba90554cb956f226de/docker-compose.yml#L25).

At least the redirection from the reverse-proxy works, but got that weird message which doesn't allow me to continue using the Moodle. I'm using a SSL certificate, so I need to use HTTPS. Here is my configuration:

```
version: '2'
services:

  redis:
    image: redis:alpine
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=moodle
    volumes:
      - postgres:/var/lib/postgresql/data

  moodle:
    image: erseco/alpine-moodle
    build: .
    restart: unless-stopped
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - SITE_URL=http://moodle.test.com
      - DB_TYPE=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=moodle
      - DB_USER=admin
      - DB_PASS=test1234
      - DB_PREFIX=mdl_
      - REDIS_HOST=redis
      - REVERSEPROXY=false
      - SSLPROXY=false
      - MOODLE_EMAIL=test@gmail.com
      - MOODLE_LANGUAGE=en
      - MOODLE_SITENAME=Learning
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=test123
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=test@gmail.com
      - SMTP_PASSWORD=your_password
      - SMTP_PROTOCOL=tls
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost
      - MOODLE_MAIL_PREFIX=[moodle]
    ports:
      - 8080:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    depends_on:
      - postgres
      - redis
networks:
  default:
    external:
      name: moodleservicio
    
volumes:
  postgres: null
  moodledata: null
  moodlehtml: null
```


NPM - Docker-compose.yml


```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
    default:
        external:
            name: moodleservicio
```

And the NPM configuration:

![image](https://github.com/erseco/alpine-moodle/assets/71790456/c23bcaff-4a77-42e5-826d-6d8a571fa626)

I followed this just in case, but I don't think is related to the issue, and I also tried to get information about the issue in english but I haven't find anything that allowed me to do so.

**With all the configuration you see here, I'm able to use Moodle by http.**

Thanks for your time, hope you can give me a hint in what I'm doing wrong.

Regards

**Comment by jjrbfi** [comment]
Just to complement a bit:

(`SSLPROXY` and `REVERSEPROXY` enabled but http in `SITEURL`)

![image](https://github.com/erseco/alpine-moodle/assets/71790456/b1dcba0c-dfcb-4b6c-8bf0-f47afdf4e3ea)


If I add https to `SITEURL`:

![image](https://github.com/erseco/alpine-moodle/assets/71790456/32db084e-6626-4b03-a35d-c53f429258de)


Thanks again for your time.

**Comment by erseco** [comment]
Hi there,

I've successfully set up a Docker Compose environment for Moodle with Nginx Proxy Manager and integrated a self-signed SSL certificate for HTTPS. Here’s the updated Docker Compose configuration:

```yaml
version: '3.8'
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  redis:
    image: redis:alpine
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=moodle
    volumes:
      - postgres:/var/lib/postgresql/data

  moodle:
    image: erseco/alpine-moodle
    build: .
    restart: unless-stopped
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - SITE_URL=https://moodle.test.com
      - DB_TYPE=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=moodle
      - DB_USER=admin
      - DB_PASS=test1234
      - DB_PREFIX=mdl_
      - REDIS_HOST=redis
      - REVERSEPROXY=false
      - SSLPROXY=true
      - MOODLE_EMAIL=test@gmail.com
      - MOODLE_LANGUAGE=en
      - MOODLE_SITENAME=Learning
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=test123
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=test@gmail.com
      - SMTP_PASSWORD=your_password
      - SMTP_PROTOCOL=tls
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost
      - MOODLE_MAIL_PREFIX=[moodle]
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    depends_on:
      - postgres
      - redis
    
volumes:
  postgres: null
  moodledata: null
  moodlehtml: null
```

Additionally, I generated a self-signed SSL certificate for `moodle.test.com` and added it to the Nginx Proxy Manager. Here's how I did it:

1. **Generate a Private Key and Certificate**:
   ```bash
   openssl genrsa -out moodle.test.com.key 2048
   openssl req -new -x509 -key moodle.test.com.key -out moodle.test.com.crt -days 365 -subj "/CN=moodle.test.com"
   ```

2. **Add the Certificate to Nginx Proxy Manager**:
   - Navigate to the SSL Certificates section in the Nginx Proxy Manager dashboard.
   - Click "Add SSL Certificate" and select "Custom".
   - Fill in the Certificate and Private Key fields with the contents of `moodle.test.com.crt` and `moodle.test.com.key`.

3. **Update `/etc/hosts` File**:
   - Edit the hosts file: `sudo vim /etc/hosts`.
   - Add: `127.0.0.1    moodle.test.com`.
   - Save and exit the editor.

This setup should work with HTTPS, allowing Moodle to run over a secure connection. Keep in mind that since the SSL certificate is self-signed, browsers will display a security warning, which is standard for development environments.

You can see that it's working here:
![screen1](https://github.com/erseco/alpine-moodle/assets/1876752/8e556b12-65da-4752-acfc-57b31c9e7218)

And the NPM config here:
![screen2](https://github.com/erseco/alpine-moodle/assets/1876752/e034f627-ef1e-4d6a-a378-5eaca26842ae)


If you encounter any issues or have questions, feel free to ask. I'm here to help!

Best regards.
