### ISSUE TITLE
[BUG] Configuración Puerto de base de datos PostgreSQL

### ISSUE THREAD

**Issue by pumarfa** [erseco/alpine-moodle#78]
**Describe el error**
Moodle no puede conectarse a la base de datos PostgreSQL

**Cómo reproducir**
En el archivo de configuración, se ha pasado los parámetros de un servidor de base de datos PostgreSQL como se detalla a continuación:

```
moodle:
    image: erseco/alpine-moodle
    build: .
    restart: unless-stopped
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      SITE_URL: http://localhost
      DB_TYPE: pgsql
      DB_HOST: 172.27.6.250
      DB_PORT: 5060
      DB_NAME: aula-fcf-unam-edu-ar
      DB_USER: aula-fcf-unam-edu-ar
      DB_PASS: aula-fcf-unam-edu-ar
  ```
La IP del Servidor PostgreSQL es: 172.27.6.250
El puerto donde atiende PostgreSQL es: 5060

**Comportamiento esperado**
Al probar el Docker Compose en local, con el servidor Postgre en un contenedor local, todo ha funcionado perfectamente. Sin embargo cuando trato de conectarlo a una base de datos distinta en un puerto específico "5060" se produce el error.

**Capturas de pantalla**

> Great, 172.27.6.250 is ready!
> moodle-1  | Executing pre-configure commands...
> moodle-1  | This is a pre-configure command
> moodle-1  | Upgrading config.php...
> moodle-1  | PHP Warning:  pg_connect(): Unable to connect to PostgreSQL server: connection to server at "172.27.6.250", port 5432 failed: Connection refused
> moodle-1  |     Is the server running on that host and accepting TCP/IP connections? in /var/www/html/lib/dml/pgsql_native_moodle_database.php on line 214
> moodle-1  | !!! <p>Error: Database connection failed</p>
> moodle-1  | <p>It is possible that the database is overloaded or otherwise not running properly.</p>
> moodle-1  | <p>The site administrator should also check that the database details have been correctly specified in config.php</p> !!!
> moodle-1  | Configuring settings...
> moodle-1  | PHP Warning:  pg_connect(): Unable to connect to PostgreSQL server: connection to server at "172.27.6.250", port 5432 failed: Connection refused
> moodle-1  |     Is the server running on that host and accepting TCP/IP connections? in /var/www/html/lib/dml/pgsql_native_moodle_database.php on line 214
> moodle-1  | !!! <p>Error: Database connection failed</p>
> moodle-1  | <p>It is possible that the database is overloaded or otherwise not running properly.</p>
> moodle-1  | <p>The site administrator should also check that the database details have been correctly specified in config.php</p> !!!
> moodle-1  | *** Failed with return value: 0
> 

**Escritorio (por favor complete la siguiente información):**
* SO: Linux Debian 12

**Contexto adicional**

He introducido un cambio en el Dockerfile, para incluír un theme de terceros al desplegar Moodle. 
Estoy realizando cambios, ya que debo reemplazar varios Moodle que ya están en producción por una versión en Docker, es por ello que necesito un Theme de terceros ya instalado.

```

RUN curl --location $MOODLE_URL | tar xz --strip-components=1 -C /var/www/html/
# --- Añadir aquí la copia del tema ---
COPY --chown=nobody ./themes/mb2nl /var/www/html/theme/mb2nl

```
